<?php
$this->menu()->setActiveItem('Agendamentos');

$this->pageTitle()->setTitle('Agendamentos');
$this->pageTitle()->setSubTitle('Todos os agendamentos realizados.');
?>


<div class="row">
    <div class="col-12">
        <div class="card card-primary card-outline" style="font-size: 14px;">
            <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                    <div class="row">
                        <form action="<?= $this->url('administrador', ['action' => 'agendamentos']) ?>" method="get">
                            <div class="input-group input-group-sm" style="width: 180px; margin-right: 10px;">
                                <input type="text" name="search" class="form-control float-right" placeholder="Pesquise..." value="<?= isset($this->search) && !empty($this->search) ? $this->search : '' ?>">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                                <div class="input-group-append">
                                    <a href="<?= $this->url('administrador', ['action' => 'agendamentos']) ?>" class="btn btn-default"><i class="fas fa-times"></i></a>
                                </div>
                            </div>
                        </form>
                        
                        <form action="<?= $this->url('administrador', ['action' => 'agendamentos']) ?>" method="get">
                            <div class="input-group input-group-sm" style="width: 250px;">
                                <input type="date" id="data" name="data" class="form-control" value="<?= isset($this->data) && !empty($this->data) ? $this->data : '' ?>">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                                <div class="input-group-append">
                                    <a href="<?= $this->url('administrador', ['action' => 'agendamentos']) ?>" class="btn btn-default"><i class="fas fa-times"></i></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-sm" style="font-size: 12px;">
                    <thead>
                        <tr>
                            <th class="text-center">Código</th>
                            <th class="text-center">Data</th>
                            <th class="text-center">Horário</th>
                            <th class="text-center">Laboratório</th>
                            <th class="text-center">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            foreach($agendamentos as $agendamento) 
                            {
                        ?>
                            <tr>
                                <td class="text-center align-middle"><?= $agendamento['id_agendamento'] ?></td>
                                <td class="text-center align-middle"><?= date('d-m-Y', strtotime($agendamento['dthr_agendamento'])) ?></td>
                                <td class="text-center align-middle">
                                    <?php
                                    switch($agendamento['horario'])
                                    {
                                        case 'manha':
                                            echo 'Manhã - 07:00 às 12:00';
                                            break;
                                        case 'tarde':
                                            echo 'Tarde - 13:00 às 17:00';
                                            break;
                                        case 'noite':
                                            echo 'Noite - 18:00 às 22:00';
                                            break;
                                    }
                                    ?>
                                </td>
                                <td class="text-center align-middle"><?= $agendamento['lab'] . ' - ' . $agendamento['tipo'] ?></td>
                                <td class="text-center align-middle">
                                    <?php
                                        switch($agendamento['status'])
                                        {
                                            case 'D':
                                                echo '<i class="fas fa-check-circle text-success" data-toggle="tooltip" data-placement="left" title="Disponível"></i>';
                                                break;
                                            case 'I':
                                                echo '<i class="fas fa-door-closed text-warning"  data-toggle="tooltip" data-placement="left" title="Indisponível"></i>';
                                                break;
                                        }
                                    ?>
                                </td>
                            </tr>
                        <?php
                            }
                            
                            if(count($agendamentos) == 0)
                            {
                        ?>
                            <tr>
                                <td colspan="12" class="text-center align-middle">
                                    Nenhum agendamento encontrado.
                                </td>
                            </tr>
                        <?php
                            }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?php echo $this->paginationControl($this->agendamentos, 'Sliding', 'partials/paginator', ['route' => 'administrador', 'params' => ['action' => 'agendamentos']]) ?>
    </div>
</div>