<?php
$this->menu()->setActiveItem('Consultar');
$this->menu()->setActiveSubItem('Laboratório');

$this->pageTitle()->setTitle("Alterar Laboratório");
$this->pageTitle()->setSubTitle('Informações do laboratório.');

$this->breadcrumbs()->setItems([
    'Consultar laboratórios' => $this->url('administrador', ['action' => 'consultar-laboratorios']),
    'Alterar Laboratório'     => ''
]);

$this->breadcrumbs()->setActiveItem('Alterar Laboratório');

$form->get('salvar')->setAttributes([
    'class'   => 'btn btn-sm btn-primary',
    'onClick' => "load('alterar-laboratorio-form')"
]);

$form->prepare();
?>

<div class="row">
    <div class="card card-primary card-outline col-sm-8 offset-sm-2">
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('lab'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('tipo'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('descricao'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-2 text-right" id="buttons">
                    <?= $this->formElement($form->get('voltar')); ?>
                    <?= $this->formElement($form->get('salvar')); ?>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>  