<?php
$this->menu()->setActiveItem('Cadastrar');
$this->menu()->setActiveSubItem('Laboratório');

$this->pageTitle()->setTitle('Cadastrar Laboratório');
$this->pageTitle()->setSubTitle('Realize o cadastro de laboratórios.');

$form->get('salvar')->setAttributes([
    'class'   => 'btn btn-sm btn-primary',
    'onClick' => "load('cadastrar-laboratorio-form')"
]);

$form->prepare();
?>

<div class="row">
    <div class="card card-primary card-outline col-sm-8 offset-sm-2">
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('lab'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('tipo'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('descricao'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-2 text-right" id="buttons">
                    <?= $this->formElement($form->get('voltar')); ?>
                    <?= $this->formElement($form->get('salvar')); ?>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>  