<?php
$this->headLink()->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/icheck-bootstrap/icheck-bootstrap.min.css?version=' . rand(1, 10000)));

$this->menu()->setItems([
    'Início'  => $this->url('administrador'),
    'Reserva' => $this->url('administrador'),
    'Cadastro' => [
        'Usuário'     => $this->url('cadastrar-usuario'),
        'Laboratório' => 'www'
    ],
    'Consultar' => [
        'Usuário'     => 'www',
        'Laboratório' => 'www'
    ],
    'Quadro de aviso' => $this->url('administrador'),
    'Sair'            => $this->url('administrador')
]);

$this->menu()->setActiveItem('Cadastro');
$this->menu()->setActiveSubItem('Usuário');

$this->pageTitle()->setTitle('Cadastrar Usuário');
$this->pageTitle()->setSubTitle('Realize o cadastro de usuários do sistema.');
?>

<div class="row">
    <div class="card col-sm-8 offset-sm-2">
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('matricula'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('grupo'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('email'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('senha'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-2 text-right">
                    <?= $this->formElement($form->get('voltar')); ?>
                    <?= $this->formElement($form->get('salvar')); ?>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>  