<?php
$this->headLink()->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/icheck-bootstrap/icheck-bootstrap.min.css?version=' . rand(1, 10000)));

$this->menu()->setActiveItem('Cadastrar');
$this->menu()->setActiveSubItem('Usuário');

$this->pageTitle()->setTitle('Cadastrar Usuário');
$this->pageTitle()->setSubTitle('Realize o cadastro dos usuários do sistema.');
?>

<div class="row">
    <div class="card col-sm-6 offset-sm-3">
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-sm-8 offset-sm-2 col-md-8 col-lg-4">
                    <?= $this->formRow($form->get('nome'), null, null, 'partials/form-elements'); ?>
                </div>
                <div class="col-sm-8 offset-sm-2 col-md-8 col-lg-4 offset-lg-0">
                    <?= $this->formRow($form->get('sobrenome'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('matricula'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('grupo'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('email'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('senha'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-2 text-right">
                    <?= $this->formElement($form->get('voltar')); ?>
                    <?= $this->formElement($form->get('salvar')); ?>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>  