<?php
$this->menu()->setActiveItem('Consultar');
$this->menu()->setActiveSubItem('Usuário');

$this->pageTitle()->setTitle('Consultar Usuários');
$this->pageTitle()->setSubTitle('Veja todos os usuários cadastrados no sistema.');
?>

<div class="row">
    <div class="col-12">
        <div class="card" style="font-size: 14px;">
            <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                    <form action="<?= $this->url('administrador', ['action' => 'consultar-usuarios']) ?>" method="get">
                        <div class="input-group input-group-sm" style="width: 180px;">
                            <input type="text" name="search" class="form-control float-right" placeholder="Pesquise..." value="<?= isset($this->search) && !empty($this->search) ? $this->search : '' ?>">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                            <div class="input-group-append">
                                <a href="<?= $this->url('administrador', ['action' => 'consultar-usuarios']) ?>" class="btn btn-default"><i class="fas fa-times"></i></a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th class="text-right" style="width: 10px;">Código</th>
                            <th class="text-center">Último Acesso</th>
                            <th class="text-center">Nome</th>
                            <th class="text-center">Matrícula</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Grupo</th>
                            <th class="text-center" style="width: 95px;">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            foreach($usuarios as $usuario) 
                            {
                        ?>
                            <tr>
                                <td class="text-right align-middle"><?= $usuario['id_usuario'] ?></td>
                                <td class="text-center align-middle"><?= date('d-m-Y', strtotime($usuario['dthr_ult_acesso'])) ?></td>
                                <td class="text-center align-middle"><?= $usuario['nome'] . ' ' . $usuario['sobrenome'] ?></td>
                                <td class="text-center align-middle"><?= $usuario['matricula'] ?></td>
                                <td class="text-center align-middle"><?= $usuario['email'] ?></td>
                                <td class="text-center align-middle">
                                <?php 
                                    switch($usuario['id_grupo'])
                                    { 
                                        case 1: 
                                            echo 'Administrador';
                                            break;
                                        case 2: 
                                            echo 'Laboratorista';
                                            break;
                                        case 3: 
                                            echo 'Professor';
                                            break;
                                    } 
                                ?>
                                </td>
                                <td class="text-center align-middle">
                                    <a href="<?= $this->url('administrador', ['action' => 'editar-usuario', 'id' => $usuario['id_usuario']]) ?>" class="btn btn-xs btn-default m-1"><i class="fas fa-edit text-primary"></i></a>
                                    <a href="<?= $this->url('administrador', ['action' => 'excluir-usuario', 'id' => $usuario['id_usuario']]) ?>" class="btn btn-xs btn-default m-1"><i class="fas fa-times text-danger"></i></a>
                                </td>
                            </tr>
                        <?php
                            }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?php echo $this->paginationControl($this->usuarios, 'Sliding', 'partials/paginator', ['route' => 'administrador', 'params' => ['action' => 'consultar-usuarios']]) ?>
    </div>
</div>