<?php
$this->headLink()->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/icheck-bootstrap/icheck-bootstrap.min.css?version=' . rand(1, 10000)));

$this->menu()->setActiveItem('Consultar');
$this->menu()->setActiveSubItem('Usuário');

$this->pageTitle()->setTitle("Editar Usuário - <i> Código: " . $this->usuario['id_usuario'] .  '</i>');
$this->pageTitle()->setSubTitle('Informações do usuário.');

$this->breadcrumbs()->setItems([
    'Consultar Usuários' => $this->url('administrador', ['action' => 'consultar-usuarios']),
    'Editar Usuário'     => ''
]);

$this->breadcrumbs()->setActiveItem('Editar Usuário');
?>

<div class="row">
    <div class="card col-sm-8 offset-sm-2">
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('matricula'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('grupo'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('email'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('nova-senha'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-2 text-right">
                    <?= $this->formElement($form->get('voltar')); ?>
                    <?= $this->formElement($form->get('salvar')); ?>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>  