<?php
$this->menu()->setActiveItem('Consultar');
$this->menu()->setActiveSubItem('Usuário');

$this->pageTitle()->setTitle("Inativar Usuário");
$this->pageTitle()->setSubTitle('Inativar o usuário do sistema.');

$this->breadcrumbs()->setItems([
    'Consultar Usuários' => $this->url('administrador', ['action' => 'consultar-usuarios']),
    'Inativar Usuário'   => ''
]);

$this->breadcrumbs()->setActiveItem('Inativar Usuário');

$form->get('inativar')->setAttributes([
    'class'   => 'btn btn-sm btn-danger',
    'onClick' => "load('inativar-usuario-form', 'text-danger')"
]);

$form->prepare();
?>

<div class="row">
    <div class="col-12">
        <div class="callout callout-danger">
            <h5><i class="fas fa-times-circle fa-sm text-danger"></i> Você irá realizar a inativação de um usuário e o cancelamento de todos seus agendamentos, tem certeza?</h5>

            <div>
                <strong>Matrícula: </strong> <i> <?= $this->usuario['matricula'] ?> </i> <br>
                <strong>Usuário: </strong> <i> <?= $this->usuario['nome'] . ' ' . $this->usuario['sobrenome'] ?> </i>
            </div>
            
            <?= $this->form()->openTag($form); ?>
                <div class="col-12 text-right" id="buttons">
                    <?= $this->formElement($form->get('voltar')); ?>
                    <?= $this->formElement($form->get('inativar')); ?>
                </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>