<?php
$this->menu()->setActiveItem('Consultar');
$this->menu()->setActiveSubItem('Laboratório');

$this->pageTitle()->setTitle("Inativar Laboratório");
$this->pageTitle()->setSubTitle('Inativar laboratório cadastrado.');

$this->breadcrumbs()->setItems([
    'Consultar Laboratórios' => $this->url('administrador', ['action' => 'consultar-laboratorios']),
    'Inativar Laboratório'   => ''
]);

$this->breadcrumbs()->setActiveItem('Inativar Laboratório');

$form->get('inativar')->setAttributes([
    'class'   => 'btn btn-sm btn-danger',
    'onClick' => "load('inativar-laboratorio-form', 'text-danger')"
]);

$form->prepare();
?>

<div class="row">
    <div class="col-12">
        <div class="callout callout-danger">
            <h5><i class="fas fa-times-circle fa-sm text-danger"></i> Você irá realizar a inativação de um laboratório, tem certeza?</h5>

            <div>
                <strong>Laboratório: </strong> <i> <?= $this->laboratorio['lab'] ?> </i> <br>
                <strong>Tipo: </strong> <i> <?= $this->laboratorio['tipo'] ?> </i> <br>
                <strong>Descrição: </strong> <i> <?= $this->laboratorio['descricao'] ?> </i>
            </div>
            
            <?= $this->form()->openTag($form); ?>
                <div class="col-12 text-right" id="buttons">
                    <?= $this->formElement($form->get('voltar')); ?>
                    <?= $this->formElement($form->get('inativar')); ?>
                </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>