<?php
$this->menu()->setActiveItem('Início');

$this->pageTitle()->setTitle('Painel Administrativo');
$this->pageTitle()->setSubTitle('Informações referentes a administração do sistema.');

echo $this->partial('partials/box-elements', [
    'boxes' => 
    [
        [
            'background' => '#3d9970',
            'count'      => 10,
            'text'       => 'Reservas',
            'icon'       => 'calendar',
            'link'       => $this->url('administrador', ['action' => 'reservas'])
        ],
        [
            'background' => '#d49b00',
            'count'      => count($avisos),
            'text'       => 'Avisos',
            'icon'       => 'exclamation',
            'link'       => $this->url('administrador')
        ],
        [
            'background' => '#02a7d9',
            'count'      => $this->usuarios,
            'text'       => 'Usuários',
            'icon'       => 'users',
            'link'       => $this->url('administrador', ['action' => 'consultar-usuarios'])
        ],
        [
            'background' => '#bdbdbd',
            'count'      => $this->laboratorios,
            'text'       => 'Laboratórios',
            'icon'       => 'flask',
            'link'       => $this->url('administrador', ['action' => 'consultar-laboratorios'])
        ]
    ]
]);
?>

<div class="row">
    <div class="col-lg-12">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h5 class="card-title m-0">Quadro de Avisos</h5>
            </div>
            <div class="card-body" style="height: 500px; overflow: auto;">
               <div class="row">
                    <div class="col-12">
                        <?php
                        foreach($avisos as $aviso) 
                        {
                        ?>
                        <div class="post">
                            <div class="user-block">
                                <img class="img-circle" src="img/profile.png" alt="user image">
                                <span class="username">
                                    <div class="text-primary"><?= $aviso['nome'] . ' ' . $aviso['sobrenome'] ?> - <span style="font-size: 14px;"><?= $aviso['email'] ?></span></div>
                                </span>
                                <span class="description"><?= date('d-m-Y H:i:s', strtotime($aviso['dthr_aviso'])) ?></span>
                            </div>
                            <p>
                                <?= $aviso['mensagem'] ?>
                            </p>

                            <p>
                                <a href="#" class="link-black text-sm"><i class="fas fa-link mr-1"></i> Demo File 1 v2</a>
                            </p>
                        </div>
                        <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>