<?php
$this->menu()->setActiveItem('Início');

$this->pageTitle()->setTitle('Painel Administrativo');
$this->pageTitle()->setSubTitle('Informações referentes a administração do sistema.');

echo $this->partial('partials/box-elements', [
    'boxes' => 
    [
        [
            'background' => '#3d9970',
            'count'      => 10,
            'text'       => 'Reservas realizadas',
            'icon'       => 'calendar',
            'link'       => 'www'
        ],
        [
            'background' => '#d49b00',
            'count'      => 10,
            'text'       => 'Alguma coisa',
            'icon'       => 'user-plus',
            'link'       => 'wwww'
        ],
        [
            'background' => '#02a7d9',
            'count'      => $this->usuarios,
            'text'       => 'Usuários',
            'icon'       => 'users',
            'link'       => $this->url('administrador', ['action' => 'consultar-usuarios'])
        ],
        [
            'background' => '#bdbdbd',
            'count'      => $this->laboratorios,
            'text'       => 'Laboratórios',
            'icon'       => 'flask',
            'link'       => $this->url('administrador', ['action' => 'consultar-laboratorios'])
        ]
    ]
]);
?>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title m-0">Featured</h5>
            </div>
            <div class="card-body">
                <h6 class="card-title">Special title treatment</h6>

                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title m-0">Featured</h5>
            </div>
            <div class="card-body">
                <h6 class="card-title">Special title treatment</h6>

                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
</div>