<?php
$this->headScript()->appendFile('/js/projetos/chamados/add/add.js?version=' . rand(1, 10000));

$this->menu()->setItems([
    'Início'  => $this->url('administrador'),
    'Reserva' => $this->url('administrador'),
    'Cadastro' => [
        'Usuário' => 'www',
        'Laboratório'   => 'www'
    ],
    'Consultar' => [
        'Usuário' => 'www',
        'Laboratório'   => 'www'
    ],
    'Quadro de aviso' => $this->url('administrador'),
    'Sair'            => $this->url('administrador'),
]);

$this->pageTitle()->setTitle('Painel Administrativo');
$this->pageTitle()->setSubTitle('Informações referentes a administração do sistema.');
?>

<div class="row">
    <div class="col-lg-3 col-6">
        <div class="small-box" style="background-color: #3d9970">
            <div class="inner">
                <h3>150</h3>

                <p>Reservas realizadas</p>
            </div>
            <div class="icon">
                <i class="fas fa-calendar"></i>
            </div>
            <a href="#" class="small-box-footer">Mais informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    
    <div class="col-lg-3 col-6">
        <div class="small-box" style="background-color: #d49b00">
            <div class="inner">
                <h3>53<sup style="font-size: 20px">%</sup></h3>

                <p>Alguma coisa</p>
            </div>
            <div class="icon">
                <i class="fas fa-user-plus"></i>
            </div>
            <a href="#" class="small-box-footer">Mais informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    
    <div class="col-lg-3 col-6">
        <div class="small-box" style="background-color: #02a7d9">
            <div class="inner">
                <h3>44</h3>

                <p>Usuários Cadastrados</p>
            </div>
            <div class="icon">
                <i class="fas fa-users"></i>
            </div>
            <a href="#" class="small-box-footer">Mais informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>

    <div class="col-lg-3 col-6">
        <div class="small-box" style="background-color: #bdbdbd">
            <div class="inner">
                <h3>65</h3>

                <p>Laboratórios</p>
            </div>
            <div class="icon">
                <i class="fas fa-flask"></i>
            </div>
            <a href="#" class="small-box-footer">Mais informações <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title m-0">Featured</h5>
            </div>
            <div class="card-body">
                <h6 class="card-title">Special title treatment</h6>

                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title m-0">Featured</h5>
            </div>
            <div class="card-body">
                <h6 class="card-title">Special title treatment</h6>

                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
</div>