<?php
$this->headLink()->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/icheck-bootstrap/icheck-bootstrap.min.css?version=' . rand(1, 10000)));

$this->menu()->setActiveItem('Perfil');

$this->pageTitle()->setTitle('Perfil');
$this->pageTitle()->setSubTitle('Informações pessoais.');

$form->get('salvar')->setAttributes([
    'class'   => 'btn btn-sm btn-primary',
    'onClick' => "load('perfil-administrador-form')"
]);

$form->prepare();
?>

<div class="alert alert-warning alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <span style="font-size: 14px;"><i class="fas fa-exclamation-triangle"></i> <strong>Atenção!</strong> Após a alteração dos dados é necessário realizar o logout e depois o login para que as alterações sejam visíveis.</span>
</div>

<div class="row">
    <div class="col-md-3">
        <div class="card card-primary card-outline">
            <div class="card-body box-profile">
                <?= $this->form()->openTag($form); ?>
                <div class="text-center">
                    <img class="img-fluid img-circle img-thumbnail" id="img-perfil" src="<?= isset($this->usuario['arquivo']) ? 'data:' . $this->usuario['tipo'] . ';base64,' . base64_encode($this->usuario['arquivo']) : '/img/profile.png' ?>" title="Foto de Perfil" alt="Foto de Perfil" style="width: 120px; height: 120px !important;" onclick="fotoPerfil()">
                    
                    <div id="foto-perfil">
                        <div class="row">
                            <div class="col-sm-8 offset-sm-2">
                                <?= $this->formRow($form->get('foto'), null, null, 'partials/form-elements'); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <h3 class="profile-username text-center"> <?= $this->usuario['nome'] . ' ' . $this->usuario['sobrenome'] ?> </h3>

                <p class="text-muted text-center"> 
                    <?php 
                        switch($this->usuario['id_grupo'])
                        { 
                            case 1: 
                                echo 'Administrador';
                                break;
                            case 2: 
                                echo 'Laboratorista';
                                break;
                            case 3: 
                                echo 'Professor';
                                break;
                        } 
                    ?>
                </p>

                <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                        <strong>Cadastro</strong> <span class="float-right"> <?= date('d-m-Y', strtotime($usuario['dthr_cad'])) ?> </span>
                    </li>
                    <li class="list-group-item">
                        <strong>Última Alteração</strong> <span class="float-right"> <?= date('d-m-Y', strtotime($usuario['dthr_ult_alteracao'])) ?> </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    
    <div class="card card-primary card-outline col-md-9">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-8 offset-sm-2 col-md-8 col-lg-4">
                    <?= $this->formRow($form->get('nome'), null, null, 'partials/form-elements'); ?>
                </div>
                <div class="col-sm-8 offset-sm-2 col-md-8 col-lg-4 offset-lg-0">
                    <?= $this->formRow($form->get('sobrenome'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('matricula'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('grupo'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('email'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('nova-senha'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-2 text-right" id="buttons">
                    <?= $this->formElement($form->get('salvar')); ?>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>