version: '3'

volumes:
  data:
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=salab
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - mysql-compose-network

  adminer:
    image: adminer:latest
    container_name: adminer
    links: mysql:mysql
    ports:
      - "8080:8080"
    networks:
      - mysql-compose-network

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.2.0.0/16