<?php
header("Content-type: " . $this->dados['contentType']);
header("Content-Disposition: attachment; filename=\"" . $this->dados['nameFile'] . "\"");
header("Pragma: no-cache");
header("Expires: 0");

if(is_array($this->dados['arquivo']))
{ 
    $outstream = fopen("php://output", "w");

    $dados = implode("\r\n", $this->dados['arquivo']);
    
    fputs($outstream, $dados, strlen($dados));
    
    fclose($outstream);
}
else
{
    header("Content-Length: " . $this->dados['size']);
    
    print $this->dados['arquivo'];
}
