<?php
$this->headLink()->appendStylesheet($this->basePath('/css/auth/login.css?version=' . mt_rand(1, 10000)));

$form->prepare();
?>
<div class="text-center mb-2">
    <img src="/img/top-logo.png" alt="SALAB - Sistema de Agendamento de Laboratórios" title="SALAB - Sistema de Agendamento de Laboratórios" width="140px" height="80px">
    <div class="mt-2">
        Sistema de Agendamento de Laboratórios
    </div>
</div> 

<div class="card">
    <div class="card-body">
        <p class="login-box-msg">Realize o login para iniciar a sessão.</p>
        
        <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-12">
                    <?= $this->formRow($form->get('matricula'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <?= $this->formRow($form->get('senha'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-12 text-right">
                    <?= $this->formElement($form->get('entrar')); ?>
                </div>
            </div>
        <?= $this->form()->closeTag(); ?>

        <div>
            <a href="<?= $this->url('login') ?>">Esqueceu sua senha?</a>
        </div>
    </div>
</div>