<?php
$this->headLink()->appendStylesheet($this->basePath('/css/auth/login.css?version=' . mt_rand(1, 10000)));

$form->get('entrar')->setAttributes([
    'class'   => 'btn btn-sm btn-primary',
    'onClick' => "load('login-form')"
]);

$form->prepare();
?>
<div class="text-center mb-2">
    <img src="<?= $this->basePath('/img/logo-login.png') ?>" alt="SALAB - Sistema de Agendamento de Laboratórios" title="SALAB - Sistema de Agendamento de Laboratórios" width="150px" height="80px">
    <div class="mt-2"">
        Sistema de Agendamento de Laboratórios
    </div>
</div> 

<div class="card">
    <div class="card-body">
        <p class="login-box-msg">Realize o login para iniciar a sessão.</p>
        
        <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-12">
                    <?= $this->formRow($form->get('matricula'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <?= $this->formRow($form->get('senha'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-8">
                    <a href="<?= $this->url('auth', ['action' => 'recuperar-senha']) ?>">Esqueceu sua senha?</a>
                </div>
                <div class="col-4 text-right" id="buttons">
                    <?= $this->formElement($form->get('entrar')); ?>
                </div>
            </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>