<?php
$this->headLink()->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/icheck-bootstrap/icheck-bootstrap.min.css?version=' . rand(1, 10000)));
$this->headScript()->appendFile($this->basePath('js/laboratorista/ocupar-laboratorio.js?version=' . rand(1, 10000)));

$this->menu()->setActiveItem('Laboratórios');

$this->pageTitle()->setTitle('Ocupar Laboratório');
$this->pageTitle()->setSubTitle('Realize a ocupação de algum laboratório.'); 

$form->get('salvar')->setAttributes([
    'class'   => 'btn btn-sm btn-primary',
    'onClick' => "load('ocupar-laboratorio-form')"
]);

$form->prepare();
?>

<div class="row">
    <div class="card card-primary card-outline col-sm-8 offset-sm-2">
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('lab'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('tipo'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('data'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('horario'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <?= $this->formRow($form->get('status'), null, null, 'partials/form-elements'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 offset-2 text-right" id="buttons">
                    <?= $this->formElement($form->get('voltar')); ?>
                    <?= $this->formElement($form->get('salvar')); ?>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>  



