<?php
$this->headLink()->prependStylesheet($this->basePath('css/laboratorista/reservas.css?version=' . rand(1, 10000)));
$this->headScript()->appendFile($this->basePath('js/laboratorista/reservas.js?version=' . rand(1, 10000)));

$this->menu()->setActiveItem('Reservas');

$this->pageTitle()->setTitle('Reservas');
$this->pageTitle()->setSubTitle('Todas os reservas realizadas dos laboratórios.');  
?>

<div class="row">
    <div class="col-12">
        <div class="card card-primary card-outline" style="font-size: 14px;">
            <div class="card-header">
                <h3 class="card-title"></h3>
                
                <div class="card-tools">
                    <form action="<?= $this->url('laboratorista', ['action' => 'reservas']) ?>" method="get">
                        <div class="input-group input-group-sm" style="width: 250px;">
                            <input type="date" id="data" name="data" class="form-control float-right" value="<?= isset($this->search) && !empty($this->search) ? $this->search : '' ?>">
                            
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                            <div class="input-group-append">
                                <a href="<?= $this->url('laboratorista', ['action' => 'reservas']) ?>" class="btn btn-default"><i class="fas fa-times"></i></a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-sm" style="font-size: 12px;">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 10px;">Código</th>
                            <th class="text-center">Usuário</th>
                            <th class="text-center">Data</th>
                            <th class="text-center">Horário</th>
                            <th class="text-center">Disciplina</th>
                            <th class="text-center">Laboratório</th>
                            <th class="text-center">Tipo</th>
                            <th class="text-center">Observacao</th>
                            <th class="text-center">Status</th>
                            <th class="text-center" style="width: 10px;">Alterar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            foreach($laboratorios as $laboratorio)
                            {
                        ?>
                            <tr>
                                <td class="text-center align-middle"><?= $laboratorio['id_reserva'] ?></td>
                                <td class="text-center align-middle"><?= $laboratorio['nome'] . ' ' . $laboratorio['sobrenome'] ?></td>
                                <td class="text-center align-middle"><?= date('d-m-Y', strtotime($laboratorio['dt_reserva'])) ?></td>
                                <td class="text-center align-middle">
                                    <?php
                                    switch($laboratorio['horario'])
                                    {
                                        case 'manha':
                                            echo 'Manhã - 08:00 às 12:00';
                                            break;
                                        case 'tarde':
                                            echo 'Tarde - 13:00 às 17:00';
                                            break;
                                        case 'noite':
                                            echo 'Noite - 18:00 às 22:00';
                                            break;
                                    }
                                    ?>
                                </td>
                                <td class="text-center align-middle"><?= $laboratorio['disciplina'] ?></td>
                                <td class="text-center align-middle"><?= $laboratorio['lab'] ?></td>
                                <td class="text-center align-middle"><?= $laboratorio['tipo'] ?></td>
                                <td class="text-center align-middle" style="font-size: 12px;"><?= $laboratorio['observacao'] ?></td>
                                <td class="text-center align-middle">
                                <?php
                                switch($laboratorio['status'])
                                {
                                    case 'D':
                                        echo '<i class="fas fa-check-circle text-success" data-toggle="tooltip" data-placement="left" title="Agendado"></i>';
                                        break;
                                    case 'I':
                                        echo '<i class="fas fa-door-closed text-warning"  data-toggle="tooltip" data-placement="left" title="Indisponível"></i>';
                                        break;
                                }
                                ?>
                                </td>
                                <td class="text-center align-middle">
                                    <a href="<?= $this->url('laboratorista', ['action' => 'alterar-reserva', 'id' => $laboratorio['id_reserva']]) ?>" class="btn btn-xs btn-default"><i class="fas fa-edit text-primary"></i></a>
                                </td>
                            </tr>
                        <?php
                            }
                            
                            if(count($laboratorios) == 0)
                            {
                        ?>
                            <tr>
                                <td colspan="12" class="text-center align-middle">
                                    Nenhuma reserva encontrada.
                                </td>
                            </tr>
                        <?php
                            }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?php echo $this->paginationControl($this->laboratorios, 'Sliding', 'partials/paginator', ['route' => 'laboratorista', 'params' => ['action' => 'reservas'], 'search' => $this->search]) ?>
    </div>
</div>