<?php
$elem     = $this->element;

$elemName = $elem->getName();
$values   = $elem->getValue();
$attr     = $elem->getAttributes();
$options  = $elem->getOptions();
$label    = $elem->getLabel();
$messages = $elem->getMessages();

//echo "<pre>";
//print_r($values);
//exit;

switch(strtolower($attr['type']))
{
    case 'text':
    case 'password':

        ?>

        <div class="form-group">
            <?= isset($label) && !empty($label) ? "<label style=\"font-size: 14px;\" for=\"" . $attr['id'] . "\">" . $label . "</label>": "" ?>
            <div class="input-group mb-3">
                <?= isset($options['icon-side']) && !empty($options['icon-side']) ? 
                "<div class=\"input-group-append\">
                    <div class=\"input-group-text\">" 
                        . $options['icon-side'] . 
                    "</div>
                </div>" : '' ?>
                <input type="<?= $attr['type'] ?>" placeholder="<?= isset($attr['placeholder']) ? $attr['placeholder'] : '' ?>" name="<?= $attr['name'] ?>" id="<?= $attr['id'] ?>" class="<?= $attr['class'] ?> <?= !empty($messages) ? 'is-invalid' : '' ?>" value="<?= isset($values) && !empty($values) ? $values : '' ?>"  <?= isset($attr['readonly']) && !empty($attr['readonly']) ? ' readonly="readonly"' : '' ?>">
                <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-<?= $options['icon'] ?>"></span>
                    </div>
                </div>
            </div>
            <?= !empty($messages) ? "<div class=\"text-danger mb-2\" style=\"font-size: 12px; \">" . implode("<br/>", $messages) . "</div>" : ''?>
        </div>
        <?php
        
        break;
    
    case 'radio':
        
        ?>

        <div class="form-group">
            <label style="font-size: 14px;" for=""><?= $label ?></label>
            <?php
            foreach($elem->getValueOptions() as $key => $value)
                {
                    ?>
                        <div class="icheck-info">
                            <input type="radio" id="<?= $elemName . $key ?>" name="<?= $elemName ?>" value="<?php echo $key; ?>" class="<?= $attr['class'] ?>" <?php if($key == $values){ echo ' checked="checked"'; }?>>
                            <label style="font-weight: normal; font-size: 14px;" for="<?= $elemName . $key ?>"><?= $value ?></label>
                        </div>
                    <?php
                }
            ?>
            <?= !empty($messages) ? "<div class=\"text-danger mb-2\" style=\"font-size: 12px; \">" . implode("<br/>", $messages) . "</div>" : ''?>
        </div>

        <?php
        
        break;
}