<?php
$elem     = $this->element;

$elemName = $elem->getName();
$values   = $elem->getValue();
$attr     = $elem->getAttributes();
$options  = $elem->getOptions();
$label    = $elem->getLabel();
$messages = $elem->getMessages();

switch(strtolower($attr['type']))
{
    case 'text':
    case 'password':

        ?>

        <div class="form-group">
            <?= isset($label) && !empty($label) ? "<label style=\"font-size: 14px;\" for=\"" . $attr['id'] . "\">" . $label . "</label>": "" ?>
            <div class="input-group mb-3">
                <?= isset($options['icon-side']) && !empty($options['icon-side']) ? 
                "<div class=\"input-group-append\">
                    <div class=\"input-group-text\">" 
                        . $options['icon-side'] . 
                    "</div>
                </div>" : '' ?>
                <input type="<?= $attr['type'] ?>" placeholder="<?= isset($attr['placeholder']) ? $attr['placeholder'] : '' ?>" name="<?= $attr['name'] ?>" id="<?= $attr['id'] ?>" class="<?= $attr['class'] ?> <?= !empty($messages) ? 'is-invalid' : '' ?>" value="<?= isset($values) && !empty($values) ? $values : '' ?>"  <?= isset($attr['readonly']) && !empty($attr['readonly']) ? ' readonly="readonly"' : '' ?>>
                <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-<?= $options['icon'] ?>"></span>
                    </div>
                </div>
            </div>
            <?= !empty($messages) ? "<div class=\"text-danger mb-2\" style=\"font-size: 12px; \">" . implode("<br/>", $messages) . "</div>" : ''?>
        </div>

        <?php
        
        break;
    
    case 'textarea':
        
        ?>

        <div class="form-group">
            <?= isset($label) && !empty($label) ? "<label style=\"font-size: 14px;\" for=\"" . $attr['id'] . "\">" . $label . "</label>": "" ?>
            <textarea form="<?= $attr['form'] ?>" maxlength="<?= $attr['maxlength'] ?>" rows="<?= isset($options['rows']) ? $options['rows'] : 5 ?>" cols="<?= isset($options['cols']) ? $options['cols'] : 50 ?>" placeholder="<?= isset($attr['placeholder']) ? $attr['placeholder'] : '' ?>" name="<?= $attr['name'] ?>" id="<?= $attr['id'] ?>" class="<?= $attr['class'] ?> <?= !empty($messages) ? 'is-invalid' : '' ?>"> </textarea>
            <?= !empty($messages) ? "<div class=\"text-danger mb-2\" style=\"font-size: 12px; \">" . implode("<br/>", $messages) . "</div>" : ''?>
        </div>
        
        <?php
        
        break;
    
    case 'radio':
        
        ?>

        <div class="form-group">
            <label style="font-size: 14px;" for=""><?= $label ?></label>
            <?php
            foreach($elem->getValueOptions() as $key => $value)
                {
                    ?>
                        <div class="icheck-primary" id="<?=$key?>">
                            <input type="radio" id="<?= $elemName . $key ?>" name="<?= $elemName ?>" value="<?php echo $key; ?>" class="<?= $attr['class'] ?>" <?php if($key == $values){ echo ' checked="checked"'; }?>>
                            <label style="font-weight: normal; font-size: 14px;" for="<?= $elemName . $key ?>"><?= $value ?></label>
                        </div>
                    <?php
                }
            ?>
            <?= !empty($messages) ? "<div class=\"text-danger mb-2\" style=\"font-size: 12px; \">" . implode("<br/>", $messages) . "</div>" : ''?>
        </div>

        <?php
        
        break;
        
    case 'hidden':
        
        ?>

        <div class="form-group">
            <div class="input-group">
                <input type="hidden" name="<?= $attr['name'] ?>" class="<?= $attr['class'] ?> <?= !empty($messages) ? 'is-invalid' : '' ?>" value="<?= isset($values) && !empty($values) ? $values : '' ?>" <?= isset($attr['readonly']) && !empty($attr['readonly']) ? ' readonly="readonly"' : '' ?>>
            </div>
        </div>

        <?php
        
        break;
    
    case 'select':
        
        ?>

        <div class="form-group">
            <label style="font-size: 14px;" for="<?=$attr['id']?>"><?=$label?></label>
            <select id="<?=$attr['id']?>" name="<?=$attr['name']?>" class="<?=$attr['class']?>">
            <?php
            foreach($elem->getValueOptions() as $key => $value)
            {
            ?>
                <option value="<?=$key?>"><?=$value?></option>
            <?php
            }
            ?>
            </select>
            <?= !empty($messages) ? "<div class=\"text-danger mb-2\" style=\"font-size: 12px; \">" . implode("<br/>", $messages) . "</div>" : ''?>
        </div>

        <?php
        
        break;
        
    case 'date':
        
        ?>

        <div class="form-group">
            <label style="font-size: 14px;" for="<?=$attr['id']?>"><?=$label?></label>
            <?=$this->formElement($elem)?>
            <?= !empty($messages) ? "<div class=\"text-danger mb-2\" style=\"font-size: 12px; \">" . implode("<br/>", $messages) . "</div>" : ''?>
        </div>

        <?php
        
        break;
    
    case 'file':
        
        if(isset($attr['multiple']))
        {
        ?>

        <div class="form-group">
            <?= isset($label) && !empty($label) ? "<label style=\"font-size: 14px;\" for=\"" . $attr['id'] . "\">" . $label . "</label>": "" ?>
            <div class="custom-file">
                <input type="file" <?= isset($attr['onchange']) ? "onchange='{$attr['onchange']}'" : '' ?> <?= isset($attr['accept']) ? "accept='{$attr['accept']}'" : '' ?>  multiple='multiple' name="<?= $attr['name'] . '[]' ?>" id="<?= $attr['id'] ?>" class="<?= $attr['class'] ?> <?= !empty($messages) ? 'is-invalid' : '' ?>">
                <label id="file-label" class="custom-file-label" for="<?= $attr['id'] ?>">Escolha o arquivo</label>
            </div>
            <?= !empty($messages) ? "<div class=\"text-danger mb-2\" style=\"font-size: 12px; \">" . implode("<br/>", $messages) . "</div>" : ''?>
        </div>

        <?php
        }
        else
        {
        ?>

        <div class="form-group">
            <?= isset($label) && !empty($label) ? "<label style=\"font-size: 14px;\" for=\"" . $attr['id'] . "\">" . $label . "</label>": "" ?>
            <div class="custom-file">
                <input type="file" <?= isset($attr['onchange']) ? "onchange='{$attr['onchange']}'" : '' ?> <?= isset($attr['accept']) ? "accept='{$attr['accept']}'" : '' ?>  name="<?= $attr['name'] ?>" id="<?= $attr['id'] ?>" class="<?= $attr['class'] ?> <?= !empty($messages) ? 'is-invalid' : '' ?>">
                <label id="file-label" class="custom-file-label" for="<?= $attr['id'] ?>">Escolha o arquivo</label>
            </div>
            <?= !empty($messages) ? "<div class=\"text-danger mb-2\" style=\"font-size: 12px; \">" . implode("<br/>", $messages) . "</div>" : ''?>
        </div>

        <?php
        }
        
        $this->inlineScript()->captureStart();
        echo <<<JS
        $(document).ready(function() 
        {
            $("input[type='file']").on("change", function()
            {  
                var numFiles = $(this).get(0).files.length;
                $("#file-label").text(numFiles + ' arquivos selecionados.');
            });
        });
JS;
        $this->inlineScript()->captureEnd();
        
        ?>

        <?php
        
        break;
}   