<?= $this->doctype() ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SALAB - Sistema de Agendamento de Laboratórios')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        
        <?php echo "\n"; ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon/favicon.ico'])
            ->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/fontawesome-free/css/all.min.css?version=' . rand(1, 10000)))
            ->prependStylesheet($this->basePath('AdminLTE-3.0.1/dist/css/adminlte.min.css?version=' . rand(1, 10000)));
        ?>
        
        <link rel="apple-touch-icon" sizes="57x57" href="<?= $this->basePath('/img/apple-icon-57x57.png') ?>">
        <link rel="apple-touch-icon" sizes="60x60" href="<?= $this->basePath('/img/apple-icon-60x60.png') ?>">
        <link rel="apple-touch-icon" sizes="72x72" href="<?= $this->basePath('/img/apple-icon-72x72.png') ?>">
        <link rel="apple-touch-icon" sizes="76x76" href="<?= $this->basePath('/img/apple-icon-76x76.png') ?>">
        <link rel="apple-touch-icon" sizes="114x114" href="<?= $this->basePath('/img/apple-icon-114x114.png') ?>">
        <link rel="apple-touch-icon" sizes="120x120" href="<?= $this->basePath('/img/apple-icon-120x120.png') ?>">
        <link rel="apple-touch-icon" sizes="144x144" href="<?= $this->basePath('/img/apple-icon-144x144.png') ?>">
        <link rel="apple-touch-icon" sizes="152x152" href="<?= $this->basePath('/img/apple-icon-152x152.png') ?>">
        <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->basePath('/img/apple-icon-180x180.png') ?>">
        
        <link rel="icon" type="image/png" sizes="192x192" href="<?= $this->basePath('/img/android-icon-192x192.png') ?>">
        
        <link rel="icon" type="image/png" sizes="32x32" href="<?= $this->basePath('/img/favicon-32x32.png') ?>">
        <link rel="icon" type="image/png" sizes="96x96" href="<?= $this->basePath('/img/favicon-96x96.png') ?>">
        <link rel="icon" type="image/png" sizes="16x16" href="<?= $this->basePath('/img/favicon-16x16.png') ?>">
        
        <?php echo "\n"; ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/all.js?version=' . rand(1, 10000)))
            ->prependFile($this->basePath('AdminLTE-3.0.1/dist/js/adminlte.js?version=' . rand(1, 10000)))
            ->prependFile($this->basePath('AdminLTE-3.0.1/plugins/bootstrap/js/bootstrap.bundle.min.js?version=' . rand(1, 10000)))
            ->prependFile($this->basePath('AdminLTE-3.0.1/plugins/jquery/jquery.min.js?version=' . rand(1, 10000)));
        ?>
        
    </head>
    <body class="hold-transition layout-top-nav">
        <div class="wrapper">
            <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
                <div class="container">
                    <div class="navbar-brand">
                        <img src="<?= $this->basePath('/img/logo-menu.png') ?>" alt="SALAB - Sistema de Agendamento de Laboratórios" title="SALAB - Sistema de Agendamento de Laboratórios" class="" width="90px" height="60px">
                    </div>

                    <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse order-3 justify-content-end" id="navbarCollapse">
                        <?= $this->menu()->render(); ?>
                    </div>
                </div>
            </nav>

            <div class="content-wrapper">
                <div class="content-header">
                    <div class="container">
                        <div class="row mb-2">
                            <?= $this->pageTitle()->render(); ?>
                            <?= $this->breadcrumbs()->render(); ?>
                        </div>
                    </div>
                </div>

                <div class="content">
                    <div class="container">
                        <?= $this->content ?>
                    </div>
                </div>
            </div>

            <footer class="main-footer text-center p-0" style="font-size: 14px;">
                <strong>Copyright &copy; 2020 - <?= date('Y') ?> <i>SALAB</i>.</strong> Todos os direitos reservados.
            </footer>
        </div>
        <?php
        echo $this->partial('partials/toastr-flash-messenger');
        echo $this->inlineScript();
        ?>
    </body>
</html>
