<?= $this->doctype() ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SALAB - Sistema de Agendamento de Laboratórios')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <title>SALAB - Sistema de Agendamento de Laboratórios</title>
        
        <?php echo "\n"; ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/fontawesome-free/css/all.min.css'))
            ->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/toastr/toastr.min.css'))
            ->prependStylesheet($this->basePath('AdminLTE-3.0.1/dist/css/adminlte.min.css'));
        ?>
        
        <?php echo "\n"; ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('AdminLTE-3.0.1/dist/js/adminlte.js'))
            ->prependFile($this->basePath('AdminLTE-3.0.1/plugins/toastr/toastr.min.js'))
            ->prependFile($this->basePath('js/geral.js'))
            ->prependFile($this->basePath('AdminLTE-3.0.1/plugins/bootstrap/js/bootstrap.bundle.min.js'))
            ->prependFile($this->basePath('AdminLTE-3.0.1/plugins/jquery/jquery.min.js'));
        ?>
        
    </head>
    <body class="hold-transition layout-top-nav">
        <div class="wrapper">
            <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
                <div class="container">
                    <a href="../../index3.html" class="navbar-brand">
                        <img src="/img/salab.png" alt="AdminLTE Logo" class="" width="90px" height="55px">
<!--                        <span class="brand-text font-weight-light">SALAB</span>-->
                    </a>

                    <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse order-3 justify-content-end" id="navbarCollapse">
                        <?= $this->menu()->render(); ?>
                    </div>
                </div>
            </nav>

            <div class="content-wrapper">
                <div class="content-header">
                    <div class="container">
                        <div class="row mb-2">
                            <?= $this->pageTitle()->render(); ?>
                            <?= $this->breadcrumbs()->render(); ?>
                        </div>
                    </div>
                </div>

                <div class="content">
                    <div class="container">
                        <?= $this->content ?>
                    </div>
                </div>
            </div>

            <footer class="main-footer text-center p-1">
                <strong>Copyright &copy; 2020 - <?= date('Y') ?> <i>SALAB</i>.</strong> All rights reserved.
            </footer>
        </div>
    </body>
</html>
