<?= $this->doctype() ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SALAB - Sistema de Agendamento de Laboratórios')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <?php echo "\n"; ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/fontawesome-free/css/all.min.css'))
            // Theme style
            ->prependStylesheet($this->basePath('AdminLTE-3.0.1/dist/css/adminlte.min.css'));
        ?>
        
        <?php echo "\n"; ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            // Bootstrap 4
            ->prependFile($this->basePath('AdminLTE-3.0.1/plugins/bootstrap/js/bootstrap.bundle.min.js'))
            // AdminLTE App
            ->prependFile($this->basePath('AdminLTE-3.0.1/dist/js/adminlte.js'))
            // Jquery
            ->prependFile($this->basePath('AdminLTE-3.0.1/plugins/jquery/jquery.min.js'));
        ?>
        
    </head>
    <body class="hold-transition login-page">
        <div class="login-box">
            <?= $this->content ?>
        </div>
        <?php
        echo $this->partial('partials/toastr-flash-messenger');
        echo $this->inlineScript();
        ?>
    </body>
</html>
