<?= $this->doctype() ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SALAB - Sistema de Agendamento de Laboratórios')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        
        <?php echo "\n"; ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon/favicon.ico'])
            ->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/fontawesome-free/css/all.min.css'))
            // Theme style
            ->prependStylesheet($this->basePath('AdminLTE-3.0.1/dist/css/adminlte.min.css'));
        ?>
        
        <link rel="apple-touch-icon" sizes="57x57" href="/img/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/img/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/img/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/img/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/img/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/img/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/img/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/img/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/img/apple-icon-180x180.png">
        
        <link rel="icon" type="image/png" sizes="192x192"  href="/img/android-icon-192x192.png">
        
        <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/img/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16x16.png">
        
        <?php echo "\n"; ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/all.js?version=' . rand(1, 10000)))
            // Bootstrap 4
            ->prependFile($this->basePath('AdminLTE-3.0.1/plugins/bootstrap/js/bootstrap.bundle.min.js'))
            // AdminLTE App
            ->prependFile($this->basePath('AdminLTE-3.0.1/dist/js/adminlte.js'))
            // Jquery
            ->prependFile($this->basePath('AdminLTE-3.0.1/plugins/jquery/jquery.min.js'));
        ?>
        
    </head>
    <body class="hold-transition login-page">
        <div class="login-box">
            <?= $this->content ?>
        </div>
        <?php
        echo $this->partial('partials/toastr-flash-messenger');
        echo $this->inlineScript();
        ?>
    </body>
</html>
