<?php
//$this->headLink()->prependStylesheet($this->basePath('AdminLTE-3.0.1/plugins/daterangepicker/daterangepicker.css?version=' . rand(1, 10000)));
//$this->headScript()->appendFile($this->basePath('AdminLTE-3.0.1/plugins/moment/moment.min.js?version='. rand(1, 10000)));
//$this->headScript()->appendFile($this->basePath('AdminLTE-3.0.1/plugins/inputmask/min/jquery.inputmask.bundle.min.js?version='. rand(1, 10000)));
//$this->headScript()->appendFile($this->basePath('AdminLTE-3.0.1/plugins/daterangepicker/daterangepicker.js?version='. rand(1, 10000)));
//$this->headScript()->appendFile($this->basePath('js/professor/reserva.js?version='. rand(1, 10000)));

$this->menu()->setActiveItem('Reserva');

$this->pageTitle()->setTitle('Reserva');
$this->pageTitle()->setSubTitle('...');
?>


